print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Keston/Desktop/Technicolor-Hyperdrive/RailAvoid/Assets/technicolor.mb"`)
{		
	file -o "/Users/Keston/Desktop/Technicolor-Hyperdrive/RailAvoid/Assets/technicolor.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Keston/Desktop/Technicolor-Hyperdrive/RailAvoid/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/Keston/Desktop/Technicolor-Hyperdrive/RailAvoid/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/Keston/Desktop/Technicolor-Hyperdrive/RailAvoid/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
